USE CUOIKY
GO
CREATE TRIGGER DatHang ON DETAIL AFTER INSERT AS 

BEGIN
	IF((SELECT QUANTILY FROM INSERTED)>(SELECT PRODUCT.QUANTILY FROM PRODUCT join inserted on inserted.ID_PRODUCT=PRODUCT.ID
	Where INSERTED.ID_PRODUCT=PRODUCT.ID)  )
	BEGIN
		PRINT'BAN DA NHAP NHIEU HON SL SP TON KHO';
		ROLLBACK;
	END
	ELSE
	BEGIN

		UPDATE PRODUCT
		SET QUANTILY = PRODUCT.QUANTILY - (
		SELECT QUANTILY
		FROM inserted
		WHERE ID_PRODUCT = PRODUCT.ID
	)
	FROM PRODUCT
	JOIN inserted ON PRODUCT.ID = inserted.ID_PRODUCT
	END
END
GO
CREATE TRIGGER CAPNHATDATHANG on DETAIL after update AS
BEGIN
	IF((SELECT PRODUCT.QUANTILY+DELETED.QUANTILY-INSERTED.QUANTILY
		FROM PRODUCT INNER JOIN DELETED ON PRODUCT.ID=DELETED.ID_PRODUCT
		INNER JOIN INSERTED ON PRODUCT.ID=INSERTED.ID_PRODUCT)
		<0)
	BEGIN
		PRINT'CAP NHAT HANG KHONG THANH CONG'
		ROLLBACK
	END
	ELSE
   BEGIN
   UPDATE PRODUCT SET QUANTILY = PRODUCT.QUANTILY -
	   (SELECT QUANTILY FROM inserted WHERE ID_PRODUCT = PRODUCT.ID) +
	   (SELECT QUANTILY FROM deleted WHERE ID_PRODUCT = PRODUCT.ID)
	   FROM PRODUCT 
	   JOIN deleted ON PRODUCT.ID = deleted.ID_PRODUCT
	END
END
/* cập nhật hàng trong kho khi đơn hàng bị hủy*/
--DROP TRIGGER HUYHANG
GO
CREATE TRIGGER HUYHANG ON DETAIL 
AFTER DELETE AS
BEGIN
 UPDATE  PRODUCT
 SET PRODUCT.QUANTILY+=(SELECT QUANTILY FROM DELETED WHERE ID_PRODUCT=PRODUCT.ID)
					FROM PRODUCT JOIN DELETED ON PRODUCT.ID=DELETED.ID_PRODUCT
END